import Head from "next/head";
import Image from "next/image";
import Link from "next/link";
import MyToDos from "./my-todos";
import NavBar from "../components/Navbar";
import { useAuthUserContext } from "../components/AuthUserContextProvider";
import Footer from "../components/Footer";

export default function Home() {
  const { user, logOut } = useAuthUserContext();
  return (
    <div className="flex flex-col justify-between" >
      <Head>
        <title>Bug Juice </title>
        <meta
          name="description"
          content="A task and bug tracking app generated by create next app"
        />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      {user ? (
        <div className="relative flex flex-col justify-between">
          <NavBar userImg={user?.avatar} logOut={logOut} />
          <div className="absolute top-12">
            <Image src="/Bug Juice copy.png" alt="" height={140} width={210} className="z-10 " />
          </div>
          <MyToDos />
        </div >
      ) : (
        <Link href="/login">
          <button className="logo">LOGIN</button>
        </Link>
      )}
      <Footer />
    </div >
  );
}